name: Kotlin CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  DETEKT_RELEASE_TAG: v1.15.0

jobs:
  code-check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Install Detekt
        run: |
          wget -O ~/detekt https://github.com/detekt/detekt/releases/download/${DETEKT_RELEASE_TAG}/detekt
          chmod +x ~/detekt

      - name: Analyze code with Detekt
        continue-on-error: true
        run: ~/detekt --input . --report sarif:detekt.sarif.json


  unit-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Run Unit Tests
        run: ./gradlew test

  construct:
    needs: unit-tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Assemble APK
        run: ./gradlew assembleDebug

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: ./app/build/outputs/apk/debug/app-debug.apk
