name: Kotlin CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

env:
  DETEKT_RELEASE_TAG: v1.15.0

jobs:

  code-check:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Install Detekt
        run: |
          wget -O ~/detekt https://github.com/detekt/detekt/releases/download/${DETEKT_RELEASE_TAG}/detekt
          chmod +x ~/detekt

      - name: Analyze code with Detekt
        continue-on-error: true
        run: ~/detekt --input . --report sarif:detekt.sarif.json




  construct:


    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 16
        uses: actions/setup-java@v2
        with:
          java-version: '16'
          distribution: 'adopt'

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Assemble APK
        run: ./gradlew assembleDebug

      - name: Create Tag
        run: |
          git config --local user.email "zyablik7771@gmail.com"
          git config --local user.name "IvanovAdrew"
          git tag -a v$(date +'%Y%m%d%H%M%S') -m "Generated tag from GitHub Action"
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Create GitHub Release and Upload APK
        uses: softprops/action-gh-release@v1
        with:
          files: ./app/build/outputs/apk/debug/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
